// TKBEN/client/src/pages/DatasetPage.tsx
import { useEffect, useRef, useState } from 'react';
import type { MouseEvent } from 'react';
import { useDataset } from '../contexts/DatasetContext';

type DatasetPreset = {
  id: string;
  label: string;
  description: string;
  defaultConfig?: string;
};

type DatasetGroup = {
  group: string;
  datasets: DatasetPreset[];
};

type DatasetPageProps = {
  showDashboard?: boolean;
  embedded?: boolean;
};

const PREDEFINED_DATASETS: DatasetGroup[] = [
  {
    group: 'General Corpora',
    datasets: [
      {
        id: 'wikitext',
        label: 'wikitext',
        description: 'Clean Wikipedia articles, multiple sizes, common baseline.',
        defaultConfig: 'wikitext-2-v1',
      },
      {
        id: 'c4',
        label: 'c4',
        description: 'Colossal Clean Crawled Corpus, large filtered web crawl.',
      },
      {
        id: 'oscar',
        label: 'oscar',
        description: 'Multilingual web corpus filtered by language.',
      },
      {
        id: 'cc_news',
        label: 'cc_news',
        description: 'News articles from Common Crawl.',
      },
      {
        id: 'openwebtext',
        label: 'openwebtext',
        description: 'Reddit-linked web pages, GPT-style corpus.',
      },
      {
        id: 'bookcorpus',
        label: 'bookcorpus',
        description: 'Fiction books, long-form narrative text.',
      },
    ],
  },
  {
    group: 'News and Formal Writing',
    datasets: [
      {
        id: 'ag_news',
        label: 'ag_news',
        description: 'Short news classification dataset.',
      },
      {
        id: 'cnn_dailymail',
        label: 'cnn_dailymail',
        description: 'News articles with summaries, long documents.',
      },
      {
        id: 'gigaword',
        label: 'gigaword',
        description: 'Newswire text, headline-style language.',
      },
      {
        id: 'multi_news',
        label: 'multi_news',
        description: 'Multi-document news summarization.',
      },
    ],
  },
  {
    group: 'Question Answering and Reading Comprehension',
    datasets: [
      {
        id: 'squad',
        label: 'squad',
        description: 'Wikipedia-based QA dataset.',
      },
      {
        id: 'natural_questions',
        label: 'natural_questions',
        description: 'Real Google search questions with long answers.',
      },
      {
        id: 'hotpot_qa',
        label: 'hotpot_qa',
        description: 'Multi-hop reasoning over multiple passages.',
      },
    ],
  },
  {
    group: 'Instruction, Dialogue, and Conversational Data',
    datasets: [
      {
        id: 'daily_dialog',
        label: 'daily_dialog',
        description: 'Clean, human-written conversations.',
      },
      {
        id: 'empathetic_dialogues',
        label: 'empathetic_dialogues',
        description: 'Emotion-focused conversations.',
      },
      {
        id: 'openassistant_oasst1',
        label: 'openassistant_oasst1',
        description: 'Instruction-following and assistant responses.',
      },
    ],
  },
  {
    group: 'Reviews and Informal Text',
    datasets: [
      {
        id: 'yelp_review_full',
        label: 'yelp_review_full',
        description: 'User reviews of varying length.',
      },
      {
        id: 'amazon_reviews_multi',
        label: 'amazon_reviews_multi',
        description: 'Multilingual product reviews.',
      },
      {
        id: 'imdb',
        label: 'imdb',
        description: 'Long-form movie reviews.',
      },
    ],
  },
  {
    group: 'Academic and Long-Form Text',
    datasets: [
      {
        id: 'arxiv',
        label: 'arxiv',
        description: 'Scientific papers.',
      },
      {
        id: 'pubmed',
        label: 'pubmed',
        description: 'Biomedical abstracts and articles.',
      },
    ],
  },
  {
    group: 'Multilingual Benchmarks',
    datasets: [
      {
        id: 'flores',
        label: 'flores',
        description: 'High-quality multilingual parallel text.',
      },
      {
        id: 'wiki40b',
        label: 'wiki40b',
        description: 'Large multilingual Wikipedia corpus.',
      },
      {
        id: 'opus_books',
        label: 'opus_books',
        description: 'Parallel book translations.',
      },
    ],
  },
];

const DatasetPage = ({ showDashboard = true, embedded = false }: DatasetPageProps) => {
  const {
    datasetName,
    selectedCorpus,
    selectedConfig,
    loading,
    error,
    datasetLoaded,
    stats,
    histogram,
    loadProgress,
    validating,
    validationReport,
    validationProgress,
    fileInputRef,
    availableDatasets,
    datasetsLoading,
    activeValidationDataset,
    activeReportLoadDataset,
    removingDataset,
    setError,
    handleCorpusChange,
    handleConfigChange,
    handleLoadDataset,
    handleUploadClick,
    handleFileChange,
    handleSelectDataset,
    handleValidateDataset,
    handleLoadLatestDatasetReport,
    handleDeleteDataset,
  } = useDataset();

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedPreset, setSelectedPreset] = useState<string | null>(null);
  const [isInsertByNameOpen, setIsInsertByNameOpen] = useState(false);
  const manualDatasetInputRef = useRef<HTMLInputElement | null>(null);

  const corpusInputId = 'corpus-input';
  const configInputId = 'config-input';
  const manualInsertRegionId = 'dataset-manual-insert-panel';
  const formatNumber = (num: number) => num.toLocaleString();

  const documentHistogram = validationReport?.document_length_histogram ?? histogram;
  const wordHistogram = validationReport?.word_length_histogram ?? null;
  const documentCount = validationReport?.document_count ?? stats?.documentCount ?? null;
  const minDocumentLength = validationReport?.min_document_length ?? stats?.minLength ?? null;
  const maxDocumentLength = validationReport?.max_document_length ?? stats?.maxLength ?? null;
  const longestWords = validationReport?.longest_words ?? [];
  const shortestWords = validationReport?.shortest_words ?? [];
  const wordCloudTerms = validationReport?.word_cloud_terms ?? [];

  const handlePresetSelect = (preset: DatasetPreset) => {
    setSelectedPreset(preset.id);
    handleCorpusChange(preset.id);
    handleConfigChange(preset.defaultConfig ?? '');
  };

  const handlePresetDownload = (event: MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    void handleLoadDataset();
  };

  const renderHistogram = (
    title: string,
    histogramData: typeof histogram | null,
    emptyLabel: string,
    countLabel: string,
  ) => {
    if (!histogramData || histogramData.counts.length === 0) {
      return (
        <div className="chart-placeholder">
          <p>{title}</p>
          <span>{emptyLabel}</span>
        </div>
      );
    }

    const maxCount = Math.max(...histogramData.counts);

    return (
      <div className="histogram-container">
        <p className="histogram-title">{title}</p>
        <div className="histogram-chart">
          {histogramData.counts.map((count, index) => {
            const heightPercent = maxCount > 0 ? (count / maxCount) * 100 : 0;
            return (
              <div
                key={`${histogramData.bins[index]}-${count}`}
                className="histogram-bar-wrapper"
                title={`${histogramData.bins[index]}: ${formatNumber(count)} ${countLabel}`}
              >
                <div
                  className="histogram-bar"
                  style={{ height: `${heightPercent}%` }}
                />
              </div>
            );
          })}
        </div>
        <div className="histogram-labels">
          <span>{formatNumber(histogramData.min_length)} chars</span>
          <span>{formatNumber(histogramData.max_length)} chars</span>
        </div>
      </div>
    );
  };

  const renderValidationStatus = () => {
    if (validating) {
      const progressLabel =
        validationProgress !== null ? ` (${Math.round(validationProgress)}%)` : '';
      return (
        <div className="loading-container">
          <div className="spinner" />
          <p>Validating dataset{progressLabel}...</p>
          <span>Computing document length and word distribution metrics.</span>
        </div>
      );
    }

    if (validationReport) {
      return null;
    }

    return (
      <div className="chart-placeholder">
        <p>Validation results will appear here.</p>
        <span>Run evaluation from the dataset preview list.</span>
      </div>
    );
  };

  let datasetOverviewDescription = 'Run dataset validation to view results';
  if (validationReport?.dataset_name) {
    datasetOverviewDescription = `Validation results for ${validationReport.dataset_name}`;
    if (validationReport.created_at) {
      datasetOverviewDescription += ` (saved ${new Date(validationReport.created_at).toLocaleString()})`;
    }
  } else if (datasetLoaded && datasetName) {
    datasetOverviewDescription = `Stats for ${datasetName}`;
  }

  const modalDownloadProgress = loadProgress !== null
    ? ` (${Math.round(loadProgress)}%)`
    : '';
  const presetsDisabled = loading;

  useEffect(() => {
    if (isModalOpen && isInsertByNameOpen) {
      manualDatasetInputRef.current?.focus();
    }
  }, [isInsertByNameOpen, isModalOpen]);

  const pageContent = (
    <>
      <div className="page-grid dataset-page-layout">
        <section className="dataset-top-section">
          <div className="dataset-top-row">
            <div className="dataset-intro-panel">
              <p className="panel-label">Dataset Usage</p>
              <p className="panel-description">
                This page is dedicated to downloading and analyzing text datasets from Hugging
                Face. Select a predefined corpus or upload your own file, then validate the
                dataset and inspect the resulting metrics directly in the dashboard.
              </p>
            </div>
            <div className="dataset-top-divider" aria-hidden="true" />
            <div className="dataset-preview-panel">
              <header className="panel-header">
                <div>
                  <p className="panel-label">Dataset Preview</p>
                  <p className="panel-description">
                    Review datasets stored in the database and run validation on demand.
                  </p>
                </div>
                <button
                  type="button"
                  className="icon-button"
                  onClick={() => setIsModalOpen(true)}
                  aria-label="Add dataset"
                  title="Add or import a dataset"
                >
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M12 5v14M5 12h14" strokeWidth="2" strokeLinecap="round" />
                  </svg>
                </button>
              </header>
              <div className="dataset-preview-body">
                {datasetsLoading ? (
                  <div className="dataset-preview-empty">Loading datasets...</div>
                ) : availableDatasets.length === 0 ? (
                  <div className="dataset-preview-empty">
                    No datasets available. Please download or upload a dataset.
                  </div>
                ) : (
                  <div className="dataset-preview-table">
                    {availableDatasets.map((dataset) => {
                      const isValidating = activeValidationDataset === dataset.dataset_name;
                      const isLoadingReport = activeReportLoadDataset === dataset.dataset_name;
                      const isRemoving = removingDataset === dataset.dataset_name;
                      const isSelectedDataset = datasetName === dataset.dataset_name;
                      return (
                        <div
                          key={dataset.dataset_name}
                          role="button"
                          tabIndex={0}
                          aria-pressed={isSelectedDataset}
                          className={`dataset-preview-row${isSelectedDataset ? ' selected' : ''}`}
                          onClick={() => handleSelectDataset(dataset.dataset_name)}
                          onKeyDown={(event) => {
                            if (event.key === 'Enter' || event.key === ' ') {
                              event.preventDefault();
                              handleSelectDataset(dataset.dataset_name);
                            }
                          }}
                        >
                          <span className="dataset-preview-name">{dataset.dataset_name}</span>
                          <span className="dataset-preview-count">
                            {formatNumber(dataset.document_count)}
                          </span>
                          <div className="dataset-preview-actions">
                            <button
                              type="button"
                              className="icon-button subtle"
                              aria-label="Run dataset evaluation"
                              title="Run dataset validation"
                              onClick={(event) => {
                                event.stopPropagation();
                                handleSelectDataset(dataset.dataset_name);
                                void handleValidateDataset(dataset.dataset_name);
                              }}
                              disabled={isValidating || isLoadingReport || isRemoving}
                            >
                              {isValidating ? (
                                <span className="action-spinner" />
                              ) : (
                                <svg viewBox="0 0 24 24" aria-hidden="true">
                                  <path d="M5 4h14v4H5z" />
                                  <path d="M5 12h14v8H5z" />
                                </svg>
                              )}
                            </button>
                            <button
                              type="button"
                              className="icon-button subtle"
                              aria-label="Load latest saved report"
                              title="Load latest saved report"
                              onClick={(event) => {
                                event.stopPropagation();
                                handleSelectDataset(dataset.dataset_name);
                                void handleLoadLatestDatasetReport(dataset.dataset_name);
                              }}
                              disabled={isValidating || isLoadingReport || isRemoving}
                            >
                              {isLoadingReport ? (
                                <span className="action-spinner" />
                              ) : (
                                <svg viewBox="0 0 24 24" aria-hidden="true">
                                  <path d="M12 4v9m0 0-4-4m4 4 4-4M5 19h14" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                              )}
                            </button>
                            <button
                              type="button"
                              className="icon-button danger"
                              aria-label="Remove dataset"
                              title="Delete dataset from database"
                              onClick={(event) => {
                                event.stopPropagation();
                                void handleDeleteDataset(dataset.dataset_name);
                              }}
                              disabled={isValidating || isLoadingReport || isRemoving}
                            >
                              {isRemoving ? (
                                <span className="action-spinner" />
                              ) : (
                                <svg viewBox="0 0 24 24" aria-hidden="true">
                                  <path d="M5 7h14" strokeWidth="2" strokeLinecap="round" />
                                  <path d="M9 7V5h6v2" strokeWidth="2" strokeLinecap="round" />
                                  <rect x="7" y="7" width="10" height="12" rx="2" />
                                </svg>
                              )}
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            </div>
          </div>
          {error && (
            <div className="error-banner">
              <span>{error}</span>
              <button onClick={() => setError(null)}>×</button>
            </div>
          )}
        </section>

        {showDashboard && (
          <aside className="panel dashboard-panel dashboard-plain">
            <header className="panel-header">
              <div>
                <p className="panel-label">Dataset Overview</p>
                <p className="panel-description">
                  {datasetOverviewDescription}
                </p>
              </div>
            </header>
            {renderValidationStatus()}
            <div className="dashboard-grid">
              <div className="stat-card">
                <p className="stat-label">Documents</p>
                <p className="stat-value">
                  {documentCount !== null ? formatNumber(documentCount) : '—'}
                </p>
              </div>
              <div className="stat-card">
                <p className="stat-label">Min Length</p>
                <p className="stat-value">
                  {minDocumentLength !== null ? formatNumber(minDocumentLength) : '—'}
                </p>
              </div>
              <div className="stat-card">
                <p className="stat-label">Max Length</p>
                <p className="stat-value">
                  {maxDocumentLength !== null ? formatNumber(maxDocumentLength) : '—'}
                </p>
              </div>
            </div>
            <div className="chart-block">
              {renderHistogram(
                'Document Length Distribution',
                documentHistogram,
                'Load or validate a dataset to see document lengths.',
                'docs',
              )}
            </div>
            <div className="chart-block">
              {renderHistogram(
                'Word Length Distribution',
                wordHistogram,
                'Validate a dataset to see word length distribution.',
                'words',
              )}
            </div>
            <div className="word-frequency-grid">
              <div className="word-frequency-panel">
                <p className="panel-label">Longest Words</p>
                {longestWords.length ? (
                  <ul className="word-frequency-list">
                    {longestWords.map((item) => (
                      <li key={`${item.word}-${item.length}-${item.count}`}>
                        <span>{item.word}</span>
                        <span>{item.length} chars</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <div className="word-frequency-empty">No validation results yet.</div>
                )}
              </div>
              <div className="word-frequency-panel">
                <p className="panel-label">Shortest Words</p>
                {shortestWords.length ? (
                  <ul className="word-frequency-list">
                    {shortestWords.map((item) => (
                      <li key={`${item.word}-${item.length}-${item.count}`}>
                        <span>{item.word}</span>
                        <span>{item.length} chars</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <div className="word-frequency-empty">No validation results yet.</div>
                )}
              </div>
            </div>
            <div className="word-cloud-panel">
              <p className="panel-label">Word Cloud Terms</p>
              {wordCloudTerms.length ? (
                <div className="word-cloud-terms">
                  {wordCloudTerms.map((item) => (
                    <span
                      key={`${item.word}-${item.count}`}
                      className="word-cloud-term"
                      style={{ fontSize: `${12 + Math.round((item.weight / 100) * 18)}px` }}
                      title={`${item.word}: ${formatNumber(item.count)}`}
                    >
                      {item.word}
                    </span>
                  ))}
                </div>
              ) : (
                <div className="word-frequency-empty">No validation results yet.</div>
              )}
            </div>
          </aside>
        )}
      </div>

      {isModalOpen && (
        <div className="modal-overlay" role="dialog" aria-modal="true">
          <div className="modal-card dataset-modal">
            <header className="dataset-modal-header">
              <p className="panel-label">Predefined Datasets</p>
              <div className="dataset-modal-actions">
                <button
                  type="button"
                  className={`icon-button subtle${isInsertByNameOpen ? ' accent' : ''}`}
                  aria-label="Insert dataset by name"
                  aria-expanded={isInsertByNameOpen}
                  aria-controls={manualInsertRegionId}
                  title={isInsertByNameOpen ? 'Hide manual dataset input' : 'Show manual dataset input'}
                  onClick={() => setIsInsertByNameOpen((value) => !value)}
                  disabled={loading}
                >
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M4 7h16M4 12h8M4 17h8" strokeWidth="2" strokeLinecap="round" />
                    <path d="M16 12h4M18 10v4" strokeWidth="2" strokeLinecap="round" />
                  </svg>
                </button>
                <button
                  type="button"
                  className="icon-button subtle"
                  aria-label="Upload custom dataset"
                  title="Upload a CSV or Excel dataset file"
                  onClick={handleUploadClick}
                  disabled={loading}
                >
                  <svg viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M12 15V5" strokeWidth="2" strokeLinecap="round" />
                    <path d="M8 9l4-4 4 4" strokeWidth="2" strokeLinecap="round" />
                    <path d="M4 19h16" strokeWidth="2" strokeLinecap="round" />
                  </svg>
                </button>
              </div>
            </header>
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileChange}
              accept=".csv,.xlsx,.xls"
              style={{ display: 'none' }}
            />
            {loading && (
              <div className="dataset-modal-progress" role="status" aria-live="polite">
                Downloading dataset{modalDownloadProgress}...
              </div>
            )}
            <div className="dataset-modal-content">
              {isInsertByNameOpen && (
                <div
                  id={manualInsertRegionId}
                  className="dataset-manual-panel"
                  role="region"
                  aria-label="Manual dataset input"
                >
                  <p className="dataset-manual-help">
                    Enter a Hugging Face dataset ID and optional configuration.
                  </p>
                  <div className="dataset-insert-row">
                    <input
                      ref={manualDatasetInputRef}
                      id={corpusInputId}
                      className="text-input"
                      value={selectedCorpus}
                      onChange={(event) => handleCorpusChange(event.target.value)}
                      disabled={loading}
                      aria-label="Dataset name"
                      placeholder="Dataset name"
                    />
                    <input
                      id={configInputId}
                      className="text-input"
                      value={selectedConfig}
                      onChange={(event) => handleConfigChange(event.target.value)}
                      disabled={loading}
                      aria-label="Configuration"
                      placeholder="Configuration"
                    />
                    <button
                      type="button"
                      className="icon-button accent"
                      onClick={() => void handleLoadDataset()}
                      disabled={loading || !selectedCorpus.trim()}
                      aria-label="Download dataset"
                      title="Download dataset from Hugging Face"
                    >
                      <svg viewBox="0 0 24 24" aria-hidden="true">
                        <path d="M12 3v12" strokeWidth="2" strokeLinecap="round" />
                        <path d="M7 10l5 5 5-5" strokeWidth="2" strokeLinecap="round" />
                        <path d="M5 19h14" strokeWidth="2" strokeLinecap="round" />
                      </svg>
                    </button>
                  </div>
                </div>
              )}
              <div
                className="dataset-preset-list-shell"
                aria-disabled={presetsDisabled}
              >
                <div className="dataset-preset-list">
                  {PREDEFINED_DATASETS.map((group) => (
                    <div className="dataset-preset-group" key={group.group}>
                      <p className="dataset-preset-heading">{group.group}</p>
                      {group.datasets.map((preset) => {
                        const isSelected = selectedPreset === preset.id;
                        return (
                          <div
                            key={preset.id}
                            role="button"
                            tabIndex={presetsDisabled ? -1 : 0}
                            aria-disabled={presetsDisabled}
                            className={`dataset-preset-row${isSelected ? ' selected' : ''}`}
                            onClick={() => {
                              if (!presetsDisabled) {
                                handlePresetSelect(preset);
                              }
                            }}
                            onKeyDown={(event) => {
                              if (!presetsDisabled && (event.key === 'Enter' || event.key === ' ')) {
                                handlePresetSelect(preset);
                              }
                            }}
                          >
                            <div className="dataset-preset-info">
                              <span className="dataset-preset-name">{preset.label}</span>
                              <span className="dataset-preset-description">{preset.description}</span>
                            </div>
                            {isSelected && (
                              <button
                                type="button"
                                className="icon-button subtle"
                                aria-label={`Download ${preset.label}`}
                                title={`Download ${preset.label}`}
                                onClick={handlePresetDownload}
                                disabled={loading || presetsDisabled}
                              >
                                <svg viewBox="0 0 24 24" aria-hidden="true">
                                  <path d="M12 3v12" strokeWidth="2" strokeLinecap="round" />
                                  <path d="M7 10l5 5 5-5" strokeWidth="2" strokeLinecap="round" />
                                  <path d="M5 19h14" strokeWidth="2" strokeLinecap="round" />
                                </svg>
                              </button>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button
                type="button"
                className="secondary-button"
                title="Close dataset selector"
                onClick={() => {
                  setIsInsertByNameOpen(false);
                  setIsModalOpen(false);
                }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );

  if (embedded) {
    return pageContent;
  }

  return <div className="page-scroll">{pageContent}</div>;
};

export default DatasetPage;

// app/client/angular/app/pages/dataset-page.component.ts
import { Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { debounceTime } from 'rxjs';
import { DatasetStore } from '../core/state/dataset.store';
import { HistogramChartComponent } from '../components/histogram-chart.component';
import { ExportApiService } from '../core/api/export-api.service';
import { errorMessageAsync } from '../core/api/error-utils';
import { WordCloudComponent } from '../components/word-cloud.component';
import { ModalA11yDirective } from '../core/ui/modal-a11y.directive';
import { formatBenchmarkAxisValue } from '../core/utils/benchmark-dashboard-data';
import {
  buildWordCloudFromWordFrequencies,
  buildZipfCurveFromWordFrequencies,
  hasMetricValue,
  isRecord,
  metricDisplayValue,
  normalizeCount,
  normalizePercent,
  parseWordCloudTerms,
  parseWordFrequencyItems,
  parseZipfCurve,
  toNumber,
} from '../core/utils/dataset-dashboard-data';

interface DatasetFiltersForm {
  search: FormControl<string>;
  source: FormControl<string>;
  documentsOperator: FormControl<'at_least' | 'at_most'>;
  documents: FormControl<number | null>;
}

interface DatasetPreset {
  id: string;
  label: string;
  description: string;
  configuration?: string;
}

interface DatasetPresetGroup {
  group: string;
  datasets: readonly DatasetPreset[];
}

type DatasetManagerTab = 'predefined' | 'add-by-name' | 'custom';

@Component({
  selector: 'app-dataset-page',
  imports: [ReactiveFormsModule, HistogramChartComponent, WordCloudComponent, ModalA11yDirective],
  templateUrl: './dataset-page.component.html',
})
export class DatasetPageComponent {
  protected readonly store = inject(DatasetStore);
  private readonly exportApi = inject(ExportApiService);
  private readonly destroyRef = inject(DestroyRef);
  protected readonly addDatasetOpen = signal(false);
  protected readonly validationOpen = signal(false);
  protected readonly validationDataset = signal<string | null>(null);
  protected readonly validationStep = signal<0 | 1 | 2>(0);
  protected readonly selectedMetricKeys = signal<readonly string[]>([]);
  protected readonly banner = signal<string | null>(null);
  protected readonly presets: readonly DatasetPresetGroup[] = [
    {
      group: 'General Corpora',
      datasets: [
        { id: 'wikitext', label: 'wikitext', description: 'Clean Wikipedia articles, multiple sizes, common baseline.', configuration: 'wikitext-2-v1' },
        { id: 'c4', label: 'c4 (10k sample)', description: 'First 10,000 English training documents from the Colossal Clean Crawled Corpus.' },
        { id: 'oscar', label: 'oscar', description: 'Multilingual web corpus filtered by language.' },
        { id: 'cc_news', label: 'cc_news', description: 'News articles from Common Crawl.' },
        { id: 'openwebtext', label: 'openwebtext', description: 'Reddit-linked web pages, GPT-style corpus.' },
        { id: 'bookcorpus', label: 'bookcorpus', description: 'Fiction books, long-form narrative text.' },
      ],
    },
    {
      group: 'News and Formal Writing',
      datasets: [
        { id: 'ag_news', label: 'ag_news', description: 'Short news classification dataset.' },
        { id: 'cnn_dailymail', label: 'cnn_dailymail', description: 'News articles with summaries, long documents.' },
        { id: 'gigaword', label: 'gigaword', description: 'Newswire text, headline-style language.' },
        { id: 'multi_news', label: 'multi_news', description: 'Multi-document news summarization.' },
      ],
    },
    {
      group: 'Question Answering and Reading Comprehension',
      datasets: [
        { id: 'squad', label: 'squad', description: 'Wikipedia-based QA dataset.' },
        { id: 'natural_questions', label: 'natural_questions', description: 'Real Google search questions with long answers.' },
        { id: 'hotpot_qa', label: 'hotpot_qa', description: 'Multi-hop reasoning over multiple passages.' },
      ],
    },
    {
      group: 'Instruction, Dialogue, and Conversational Data',
      datasets: [
        { id: 'daily_dialog', label: 'daily_dialog', description: 'Clean, human-written conversations.' },
        { id: 'empathetic_dialogues', label: 'empathetic_dialogues', description: 'Emotion-focused conversations.' },
        { id: 'openassistant_oasst1', label: 'openassistant_oasst1', description: 'Instruction-following and assistant responses.' },
      ],
    },
    {
      group: 'Reviews and Informal Text',
      datasets: [
        { id: 'yelp_review_full', label: 'yelp_review_full', description: 'User reviews of varying length.' },
        { id: 'amazon_reviews_multi', label: 'amazon_reviews_multi', description: 'Multilingual product reviews.' },
        { id: 'imdb', label: 'imdb', description: 'Long-form movie reviews.' },
      ],
    },
    {
      group: 'Academic and Long-Form Text',
      datasets: [
        { id: 'arxiv', label: 'arxiv', description: 'Scientific papers.' },
        { id: 'pubmed', label: 'pubmed', description: 'Biomedical abstracts and articles.' },
      ],
    },
    {
      group: 'Multilingual Benchmarks',
      datasets: [
        { id: 'flores', label: 'flores', description: 'High-quality multilingual parallel text.' },
        { id: 'wiki40b', label: 'wiki40b', description: 'Large multilingual Wikipedia corpus.' },
        { id: 'opus_books', label: 'opus_books', description: 'Parallel book translations.' },
      ],
    },
  ];
  protected readonly selectedPreset = signal<string | null>('wikitext');
  protected readonly collapsedPresetGroups = signal<Readonly<Record<string, boolean>>>({});
  protected readonly activeDatasetTab = signal<DatasetManagerTab>('predefined');
  protected readonly downloadForm = new FormGroup({
    corpus: new FormControl('wikitext', { nonNullable: true, validators: [Validators.required] }),
    configuration: new FormControl('wikitext-2-v1', { nonNullable: true }),
  });
  protected readonly validationForm = new FormGroup({
    sessionName: new FormControl('', { nonNullable: true }),
    samplingMode: new FormControl<'fraction' | 'count'>('fraction', { nonNullable: true }),
    samplingFraction: new FormControl(1, { nonNullable: true, validators: [Validators.min(0.01), Validators.max(1)] }),
    samplingCount: new FormControl(1000, { nonNullable: true, validators: [Validators.min(1), Validators.max(100000)] }),
    minLength: new FormControl<number | null>(null, { validators: [Validators.min(0)] }),
    maxLength: new FormControl<number | null>(null, { validators: [Validators.min(0)] }),
    excludeEmpty: new FormControl(true, { nonNullable: true }),
  });
  protected readonly filters = new FormGroup<DatasetFiltersForm>({
    search: new FormControl('', { nonNullable: true }),
    source: new FormControl('', { nonNullable: true }),
    documentsOperator: new FormControl('at_least', { nonNullable: true }),
    documents: new FormControl<number | null>(null),
  });
  protected readonly aggregate = computed<Record<string, unknown>>(() => {
    const value = this.store.report()?.aggregate_statistics;
    return isRecord(value) ? value : {};
  });
  protected readonly characterSlices = computed(() => [
    { key: 'Whitespace', value: toNumber(this.aggregate()['chars.whitespace_ratio']) },
    { key: 'Punctuation', value: toNumber(this.aggregate()['chars.punctuation_ratio']) },
    { key: 'Digits', value: toNumber(this.aggregate()['chars.digit_ratio']) },
    { key: 'Uppercase', value: toNumber(this.aggregate()['chars.uppercase_ratio']) },
    { key: 'Non-ASCII', value: toNumber(this.aggregate()['chars.non_ascii_ratio']) },
    { key: 'Control', value: toNumber(this.aggregate()['chars.control_ratio']) },
    { key: 'Other', value: toNumber(this.aggregate()['chars.other_ratio']) },
  ].filter((item) => item.value > 0));
  protected readonly characterTotal = computed(() => Math.max(1, this.characterSlices().reduce((sum, item) => sum + item.value, 0)));
  protected readonly zipfCurve = computed(() => {
    const aggregate = this.aggregate();
    const parsed = parseZipfCurve(aggregate['words.zipf_curve']);
    if (parsed.length) return parsed;
    return buildZipfCurveFromWordFrequencies(this.wordFrequencies());
  });
  protected readonly wordFrequencies = computed(() => {
    const report = this.store.report();
    if (!report) return [];
    if (report.most_common_words?.length) return parseWordFrequencyItems(report.most_common_words);
    return parseWordFrequencyItems(this.aggregate()['words.most_common']);
  });
  protected readonly wordCloudTerms = computed(() => {
    const report = this.store.report();
    if (!report) return [];
    const terms = report.word_cloud_terms?.length ? parseWordCloudTerms(report.word_cloud_terms) : parseWordCloudTerms(this.aggregate()['words.word_cloud']);
    return terms.length ? terms : buildWordCloudFromWordFrequencies(this.wordFrequencies());
  });
  protected readonly documentCount = computed(() => hasMetricValue(this.aggregate()['corpus.document_count']) ? toNumber(this.aggregate()['corpus.document_count']) : this.store.report()?.document_count ?? 0);
  protected readonly emptyCount = computed(() => {
    const raw = this.aggregate()['quality.empty_rate'];
    return hasMetricValue(raw) ? Math.round(toNumber(raw) * this.documentCount()) : null;
  });
  protected readonly aggregateRows = computed(() => {
    const aggregate = this.aggregate();
    return [
      { label: 'Num documents', value: this.store.report() ? normalizeCount(this.documentCount()) : '—' },
      { label: 'Mean length', value: metricDisplayValue(aggregate['doc.length_mean'], (value) => value.toFixed(2)) },
      { label: 'Min length', value: metricDisplayValue(aggregate['doc.length_min'], normalizeCount) },
      { label: 'Max length', value: metricDisplayValue(aggregate['doc.length_max'], normalizeCount) },
      { label: 'Empty count', value: this.emptyCount() === null ? '—' : normalizeCount(this.emptyCount() ?? 0) },
      { label: 'Length CV', value: metricDisplayValue(aggregate['doc.length_cv'], (value) => value.toFixed(4)) },
      { label: 'p50', value: metricDisplayValue(aggregate['doc.length_p50'], normalizeCount) },
      { label: 'p90', value: metricDisplayValue(aggregate['doc.length_p90'], normalizeCount) },
      { label: 'p99', value: metricDisplayValue(aggregate['doc.length_p99'], normalizeCount) },
    ];
  });
  protected readonly wordMetricRows = computed(() => {
    const aggregate = this.aggregate();
    return [
      { label: 'Vocabulary size', value: metricDisplayValue(aggregate['corpus.unique_words'], normalizeCount) },
      { label: 'MATTR', value: metricDisplayValue(aggregate['corpus.mattr'], (value) => value.toFixed(4)) },
      { label: 'Entropy', value: metricDisplayValue(aggregate['words.shannon_entropy'], (value) => value.toFixed(4)) },
      { label: 'Hapax ratio', value: metricDisplayValue(aggregate['words.hapax_ratio'], (value) => value.toFixed(4)) },
      { label: 'Zipf slope', value: metricDisplayValue(aggregate['words.zipf_slope'], (value) => value.toFixed(4)) },
      { label: 'Gini', value: metricDisplayValue(aggregate['words.frequency_gini'], (value) => value.toFixed(4)) },
      { label: 'HHI', value: metricDisplayValue(aggregate['words.hhi'], (value) => value.toFixed(6)) },
    ];
  });
  protected readonly entropy = computed(() => toNumber(this.aggregate()['words.normalized_entropy']));
  protected readonly shannonEntropy = computed(() => toNumber(this.aggregate()['words.shannon_entropy']));
  protected readonly duplicateRate = computed(() => toNumber(this.aggregate()['quality.duplicate_rate']));
  protected readonly nearDuplicateRate = computed(() => toNumber(this.aggregate()['quality.near_duplicate_rate']));
  protected readonly topKConcentration = computed(() => toNumber(this.aggregate()['words.topk_concentration']));
  protected readonly rareTailMass = computed(() => toNumber(this.aggregate()['words.rare_tail_mass']));
  protected readonly allMetricKeys = computed(() => this.store.metricCategories().flatMap((category) => category.metrics.map((metric) => metric.key)));

  protected readonly donutColors = ['#f59e0b', '#fb7185', '#38bdf8', '#34d399', '#a78bfa', '#f97316', '#64748b'];
  protected readonly zipfAxisFractions = [0, 0.25, 0.5, 0.75, 1] as const;
  protected readonly formatAxis = formatBenchmarkAxisValue;
  protected readonly zipfMaxRank = computed(() => Math.max(1, ...this.zipfCurve().map((item) => item.rank)));
  protected readonly zipfMaxFrequency = computed(() => Math.max(1, ...this.zipfCurve().map((item) => item.frequency)));
  protected readonly zipfPoints = computed(() => {
    const values = this.zipfCurve();
    const maxRank = this.zipfMaxRank();
    const maxFrequency = this.zipfMaxFrequency();
    return values.map((item) => `${24 + (item.rank / maxRank) * 572},${166 - (item.frequency / maxFrequency) * 140}`).join(' ');
  });

  protected zipfX(fraction: number): number { return 24 + fraction * 572; }
  protected zipfY(fraction: number): number { return 166 - fraction * 140; }
  protected zipfRank(fraction: number): string { return Math.max(1, Math.round(this.zipfMaxRank() * fraction)).toLocaleString(); }
  protected zipfFrequency(fraction: number): string { return this.formatAxis(this.zipfMaxFrequency() * fraction, 'number'); }

  protected donutPath(index: number): string {
    const slices = this.characterSlices();
    const total = this.characterTotal();
    const start = slices.slice(0, index).reduce((sum, item) => sum + item.value, 0) / total * Math.PI * 2 - Math.PI / 2;
    const end = start + slices[index].value / total * Math.PI * 2;
    const large = end - start > Math.PI ? 1 : 0;
    const outer = (angle: number) => `${100 + Math.cos(angle) * 96} ${140 + Math.sin(angle) * 96}`;
    const inner = (angle: number) => `${100 + Math.cos(angle) * 58} ${140 + Math.sin(angle) * 58}`;
    return `M ${outer(start)} A 96 96 0 ${large} 1 ${outer(end)} L ${inner(end)} A 58 58 0 ${large} 0 ${inner(start)} Z`;
  }

  protected displayPercent(value: unknown): string { return normalizePercent(toNumber(value)); }
  protected hasAggregateMetric(key: string): boolean { return hasMetricValue(this.aggregate()[key]); }
  protected dashboardDescription(): string {
    const report = this.store.report();
    if (!report) return 'Load a saved report or run validation to populate this dashboard.';
    const timestamp = report.created_at ? ` (${new Date(report.created_at).toLocaleString()})` : '';
    return `Latest persisted session for ${report.dataset_name}${timestamp}`;
  }

  constructor() {
    this.filters.valueChanges.pipe(debounceTime(10), takeUntilDestroyed(this.destroyRef)).subscribe(() => this.refresh());
  }

  protected refresh(): void {
    const value = this.filters.getRawValue();
    this.store.refresh({
      search: value.search,
      source: value.source === 'public' || value.source === 'custom' ? value.source : undefined,
      documentsOperator: value.documentsOperator,
      documents: value.documents ?? undefined,
    });
  }

  protected openAddDataset(): void {
    this.activeDatasetTab.set('predefined');
    this.addDatasetOpen.set(true);
  }

  protected selectDatasetTab(tab: DatasetManagerTab): void {
    this.activeDatasetTab.set(tab);
  }

  protected handleDatasetTabKeydown(event: KeyboardEvent, tab: DatasetManagerTab): void {
    const tabs: readonly DatasetManagerTab[] = ['predefined', 'add-by-name', 'custom'];
    const index = tabs.indexOf(tab);
    let nextIndex: number | null = null;
    if (event.key === 'ArrowRight' || event.key === 'ArrowDown') nextIndex = (index + 1) % tabs.length;
    if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') nextIndex = (index - 1 + tabs.length) % tabs.length;
    if (event.key === 'Home') nextIndex = 0;
    if (event.key === 'End') nextIndex = tabs.length - 1;
    if (nextIndex === null) return;
    event.preventDefault();
    const nextTab = tabs[nextIndex];
    this.activeDatasetTab.set(nextTab);
    document.getElementById(`dataset-tab-${nextTab}`)?.focus();
  }

  protected selectDataset(datasetName: string): void {
    this.store.select(datasetName);
    this.banner.set(null);
    this.store.loadLatest(datasetName, { suppressNotFoundError: true });
  }

  protected openValidation(datasetName: string): void {
    this.validationDataset.set(datasetName);
    this.validationStep.set(0);
    this.selectedMetricKeys.set([...this.allMetricKeys()]);
    this.validationForm.reset({ sessionName: '', samplingMode: 'fraction', samplingFraction: 1, samplingCount: 1000, minLength: null, maxLength: null, excludeEmpty: true });
    this.validationOpen.set(true);
  }

  protected toggleMetric(metricKey: string, enabled: boolean): void {
    const current = new Set(this.selectedMetricKeys());
    if (enabled) current.add(metricKey); else current.delete(metricKey);
    this.selectedMetricKeys.set([...current]);
  }

  protected toggleMetricCategory(category: { metrics: readonly { key: string }[] }, enabled: boolean): void {
    const current = new Set(this.selectedMetricKeys());
    for (const metric of category.metrics) {
      if (enabled) current.add(metric.key); else current.delete(metric.key);
    }
    this.selectedMetricKeys.set([...current]);
  }

  protected categorySelected(category: { metrics: readonly { key: string }[] }): boolean {
    return category.metrics.length > 0 && category.metrics.every((metric) => this.selectedMetricKeys().includes(metric.key));
  }

  protected nextValidationStep(): void {
    if (this.validationStep() === 0 && this.store.metricCategories().length > 0 && this.selectedMetricKeys().length === 0) return;
    if (this.validationStep() < 2) this.validationStep.update((step) => (step + 1) as 0 | 1 | 2);
  }

  protected previousValidationStep(): void {
    if (this.validationStep() > 0) this.validationStep.update((step) => (step - 1) as 0 | 1 | 2);
  }

  protected runValidation(): void {
    const datasetName = this.validationDataset();
    if (!datasetName) return;
    const value = this.validationForm.getRawValue();
    const sessionName = value.sessionName.trim();
    const minLength = value.minLength === null || !Number.isFinite(value.minLength) ? null : Math.max(0, Math.floor(value.minLength));
    const maxLength = value.maxLength === null || !Number.isFinite(value.maxLength) ? null : Math.max(0, Math.floor(value.maxLength));
    this.store.analyze({
      dataset_name: datasetName,
      session_name: sessionName || null,
      selected_metric_keys: this.selectedMetricKeys().length ? [...this.selectedMetricKeys()] : null,
      sampling: value.samplingMode === 'fraction'
        ? { fraction: Math.min(1, Math.max(0.01, value.samplingFraction)) }
        : { count: Math.min(100000, Math.max(1, Math.floor(value.samplingCount))) },
      filters: { min_length: minLength, max_length: maxLength, exclude_empty: value.excludeEmpty },
      metric_parameters: {},
    });
    this.validationOpen.set(false);
  }

  protected loadLatest(datasetName: string): void {
    this.store.select(datasetName);
    this.store.loadLatest(datasetName);
  }

  protected removeDataset(datasetName: string): void {
    if (window.confirm(`Remove ${datasetName} from the database?`)) this.store.remove(datasetName);
  }

  protected choosePreset(preset: DatasetPreset): void {
    this.selectedPreset.set(preset.id);
    this.downloadForm.patchValue({ corpus: preset.id, configuration: preset.configuration ?? '' });
  }

  protected downloadPreset(preset: DatasetPreset): void {
    this.choosePreset(preset);
    this.downloadSelected();
  }

  protected togglePresetGroup(group: string): void {
    this.collapsedPresetGroups.update((groups) => ({ ...groups, [group]: !groups[group] }));
  }

  protected isPresetGroupCollapsed(group: string): boolean {
    return this.collapsedPresetGroups()[group] ?? false;
  }

  protected downloadSelected(): void {
    const value = this.downloadForm.getRawValue();
    this.store.download({ corpus: value.corpus, configs: { configuration: value.configuration || null } });
  }

  protected uploadFile(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) {
      this.store.upload(file);
      input.value = '';
    }
  }

  protected exportDashboard(): void {
    const report = this.store.report();
    if (!report) return;
    this.exportApi.dashboardPdf({ dashboardType: 'dataset', reportName: `dataset-${report.dataset_name}-report-${report.report_id ?? 'latest'}`, fileName: `dataset-${report.dataset_name}-report.pdf`, dashboardPayload: report as unknown as Record<string, unknown> }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (result) => { const url = URL.createObjectURL(result.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = result.fileName; anchor.click(); URL.revokeObjectURL(url); },
      error: (error: unknown) => { void errorMessageAsync(error, 'Failed to export dashboard.').then((message) => this.banner.set(message)); },
    });
  }

  protected notify(message: string): void {
    this.banner.set(message);
  }

  protected closeAddDataset(): void {
    this.addDatasetOpen.set(false);
  }

  protected closeValidation(): void {
    this.validationOpen.set(false);
    this.validationStep.set(0);
  }
}
