// TKBEN/client/src/components/HFAccessKeyManager.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import type { HFAccessKeyListItem } from '../types/api';
import {
  activateHFAccessKey,
  addHFAccessKey,
  deactivateHFAccessKey,
  deleteHFAccessKey,
  fetchHFAccessKeys,
  revealHFAccessKey,
} from '../services/keysApi';

type HFAccessKeyManagerProps = {
  isOpen: boolean;
  onClose: () => void;
};

const HFAccessKeyManager = ({ isOpen, onClose }: HFAccessKeyManagerProps) => {
  const [newKeyValue, setNewKeyValue] = useState('');
  const [keys, setKeys] = useState<HFAccessKeyListItem[]>([]);
  const [revealedValues, setRevealedValues] = useState<Record<number, string>>({});
  const [visibleRows, setVisibleRows] = useState<Record<number, boolean>>({});
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [actionKeyId, setActionKeyId] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);

  const loadKeys = useCallback(async () => {
    setLoading(true);
    try {
      const response = await fetchHFAccessKeys();
      setKeys(response.keys);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load keys.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!isOpen) {
      return;
    }
    void loadKeys();
  }, [isOpen, loadKeys]);

  const hasKeys = useMemo(() => keys.length > 0, [keys.length]);

  const handleAddKey = async () => {
    const normalizedValue = newKeyValue.trim();
    if (!normalizedValue) {
      setError('Key cannot be empty.');
      return;
    }

    setSubmitting(true);
    setError(null);
    try {
      await addHFAccessKey(normalizedValue);
      setNewKeyValue('');
      setVisibleRows({});
      setRevealedValues({});
      await loadKeys();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to add key.');
    } finally {
      setSubmitting(false);
    }
  };

  const handleToggleReveal = async (keyId: number) => {
    if (visibleRows[keyId]) {
      setVisibleRows((current) => ({ ...current, [keyId]: false }));
      return;
    }

    setError(null);
    if (revealedValues[keyId]) {
      setVisibleRows((current) => ({ ...current, [keyId]: true }));
      return;
    }

    setActionKeyId(keyId);
    try {
      const response = await revealHFAccessKey(keyId);
      setRevealedValues((current) => ({ ...current, [keyId]: response.key_value }));
      setVisibleRows((current) => ({ ...current, [keyId]: true }));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to reveal key.');
    } finally {
      setActionKeyId(null);
    }
  };

  const handleActivate = async (keyId: number, isActive: boolean) => {
    setActionKeyId(keyId);
    setError(null);
    try {
      if (isActive) {
        await deactivateHFAccessKey(keyId);
      } else {
        await activateHFAccessKey(keyId);
      }
      await loadKeys();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update key state.');
    } finally {
      setActionKeyId(null);
    }
  };

  const handleDelete = async (key: HFAccessKeyListItem) => {
    if (key.is_active) {
      setError('The active key cannot be deleted.');
      return;
    }
    const confirmed = window.confirm('Delete this key?');
    if (!confirmed) {
      return;
    }

    setActionKeyId(key.id);
    setError(null);
    try {
      await deleteHFAccessKey(key.id);
      setVisibleRows((current) => ({ ...current, [key.id]: false }));
      setRevealedValues((current) => {
        const next = { ...current };
        delete next[key.id];
        return next;
      });
      await loadKeys();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete key.');
    } finally {
      setActionKeyId(null);
    }
  };

  if (!isOpen) {
    return null;
  }

  return (
    <>
      <button
        type="button"
        className="key-manager-backdrop"
        aria-label="Close key manager"
        onClick={onClose}
      />
      <div className="key-manager-popover" role="dialog" aria-modal="true" aria-label="Hugging Face keys">
        <header className="key-manager-header">
          <p className="panel-label">Hugging Face Keys</p>
          <button
            type="button"
            className="icon-button subtle"
            onClick={onClose}
            aria-label="Close key manager"
          >
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="M6 6l12 12M18 6L6 18" strokeWidth="2" strokeLinecap="round" />
            </svg>
          </button>
        </header>

        <div className="key-manager-add-row">
          <input
            type="text"
            className="text-input"
            placeholder="Enter Hugging Face key"
            value={newKeyValue}
            onChange={(event) => setNewKeyValue(event.target.value)}
          />
          <button
            type="button"
            className="primary-button"
            onClick={() => void handleAddKey()}
            disabled={submitting}
          >
            Add
          </button>
        </div>

        {error && (
          <div className="error-banner" role="alert">
            <span>{error}</span>
            <button type="button" aria-label="Dismiss" onClick={() => setError(null)}>
              ×
            </button>
          </div>
        )}

        <div className="key-manager-list">
          {loading ? (
            <div className="key-manager-empty">Loading keys...</div>
          ) : !hasKeys ? (
            <div className="key-manager-empty">No keys stored.</div>
          ) : (
            keys.map((key) => {
              const isVisible = Boolean(visibleRows[key.id]);
              const preview = isVisible
                ? (revealedValues[key.id] || key.masked_preview)
                : key.masked_preview;
              const inProgress = actionKeyId === key.id;

              return (
                <div className="key-manager-row" key={key.id}>
                  <div className="key-manager-preview">{preview}</div>
                  <div className="key-manager-actions">
                    <button
                      type="button"
                      className="icon-button subtle"
                      aria-label={isVisible ? 'Hide key' : 'Reveal key'}
                      onClick={() => void handleToggleReveal(key.id)}
                      disabled={inProgress}
                    >
                      <svg viewBox="0 0 24 24" aria-hidden="true">
                        {isVisible ? (
                          <>
                            <path d="M3 3l18 18" strokeWidth="2" strokeLinecap="round" />
                            <path
                              d="M9.9 5.1A10.9 10.9 0 0 1 12 5c5 0 9 4 10 7-0.4 1.3-1.5 2.8-3.1 4.1M6.2 8.2C4.4 9.5 3.3 11 2.9 12 3.9 15 7 19 12 19c0.9 0 1.8-0.1 2.6-0.3"
                              strokeWidth="2"
                              strokeLinecap="round"
                              fill="none"
                            />
                          </>
                        ) : (
                          <>
                            <path
                              d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7-10-7-10-7z"
                              fill="none"
                              strokeWidth="2"
                            />
                            <circle cx="12" cy="12" r="3" />
                          </>
                        )}
                      </svg>
                    </button>
                    <button
                      type="button"
                      className={`icon-button subtle${key.is_active ? ' accent' : ''}`}
                      aria-label={key.is_active ? 'Deactivate key (set locked)' : 'Activate key (locked)'}
                      onClick={() => void handleActivate(key.id, key.is_active)}
                      disabled={inProgress}
                    >
                      <svg viewBox="0 0 24 24" aria-hidden="true">
                        <rect x="6" y="11" width="12" height="9" rx="2" fill="none" strokeWidth="2" />
                        {key.is_active ? (
                          <path
                            d="M9 11V8a3 3 0 0 1 5.5-1.7"
                            fill="none"
                            strokeWidth="2"
                            strokeLinecap="round"
                          />
                        ) : (
                          <path
                            d="M8 11V8a4 4 0 0 1 8 0v3"
                            fill="none"
                            strokeWidth="2"
                            strokeLinecap="round"
                          />
                        )}
                      </svg>
                    </button>
                    <button
                      type="button"
                      className="icon-button danger"
                      aria-label="Delete key"
                      onClick={() => void handleDelete(key)}
                      disabled={inProgress || key.is_active}
                    >
                      <svg viewBox="0 0 24 24" aria-hidden="true">
                        <path d="M6 6l12 12M18 6L6 18" strokeWidth="2" strokeLinecap="round" />
                      </svg>
                    </button>
                  </div>
                </div>
              );
            })
          )}
        </div>
      </div>
    </>
  );
};

export default HFAccessKeyManager;

// app/client/angular/app/components/hf-access-key-manager.component.ts
import { Component, EventEmitter, Output, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { DestroyRef } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import { KeysApiService } from '../core/api/keys-api.service';
import { errorMessage } from '../core/api/error-utils';
import type { HFAccessKeyListItem } from '../core/api/api.models';

@Component({
  selector: 'app-hf-access-key-manager',
  imports: [ReactiveFormsModule],
  templateUrl: './hf-access-key-manager.component.html',
})
export class HfAccessKeyManagerComponent {
  private readonly api = inject(KeysApiService);
  private readonly destroyRef = inject(DestroyRef);
  @Output() readonly closed = new EventEmitter<void>();
  protected readonly key = new FormControl('', { nonNullable: true, validators: [Validators.required] });
  protected readonly keys = signal<readonly HFAccessKeyListItem[]>([]);
  protected readonly revealed = signal<Record<number, string>>({});
  protected readonly loading = signal(true);
  protected readonly submitting = signal(false);
  protected readonly actionKeyId = signal<number | null>(null);
  protected readonly error = signal<string | null>(null);

  constructor() { this.load(); }

  private load(): void {
    this.loading.set(true);
    this.api.list().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (response) => { this.keys.set(response.keys); this.loading.set(false); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to load keys.')); this.loading.set(false); } });
  }

  protected addKey(): void {
    if (this.key.invalid) {
      this.key.markAsTouched();
      return;
    }
    this.submitting.set(true);
    this.api.add(this.key.value).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.key.reset(); this.submitting.set(false); this.load(); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to add key.')); this.submitting.set(false); } });
  }

  protected toggleReveal(item: HFAccessKeyListItem): void {
    const existing = this.revealed()[item.id];
    if (existing) { const next = { ...this.revealed() }; delete next[item.id]; this.revealed.set(next); return; }
    this.actionKeyId.set(item.id);
    this.api.reveal(item.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (response) => { this.revealed.set({ ...this.revealed(), [item.id]: response.key_value }); this.actionKeyId.set(null); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to reveal key.')); this.actionKeyId.set(null); } });
  }

  protected toggleActivation(item: HFAccessKeyListItem): void {
    this.actionKeyId.set(item.id);
    const request$ = item.is_active ? this.api.deactivate(item.id) : this.api.activate(item.id);
    request$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.actionKeyId.set(null); this.load(); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to update key.')); this.actionKeyId.set(null); } });
  }

  protected deleteKey(item: HFAccessKeyListItem): void {
    if (!window.confirm(`Delete ${item.masked_preview}?`)) return;
    this.actionKeyId.set(item.id);
    this.api.remove(item.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.actionKeyId.set(null); this.load(); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to delete key.')); this.actionKeyId.set(null); } });
  }

  protected close(): void {
    this.closed.emit();
  }
}

<button class="key-manager-backdrop" type="button" aria-label="Close key manager" (click)="close()"></button>
<section class="key-manager-popover" role="dialog" aria-modal="true" aria-labelledby="hf-key-title">
  <header class="key-manager-header">
    <div>
      <p id="hf-key-title" class="panel-label">Hugging Face Keys</p>
      <p class="panel-description">Store access keys for gated Hugging Face downloads.</p>
    </div>
    <button class="icon-button subtle" type="button" aria-label="Close key manager" (click)="close()">×</button>
  </header>
  <div class="key-manager-add-row">
    <input id="hf-key-input" class="text-input" type="password" placeholder="Enter Hugging Face key" [formControl]="key" aria-label="Hugging Face key" />
    <button class="primary-button" type="button" (click)="addKey()">Add</button>
  </div>
  @if (error()) { <p class="error-banner" role="alert">{{ error() }}</p> }
  @if (key.invalid && key.touched) {
    <p class="error-banner" role="alert">Enter a Hugging Face key.</p>
  }
  <div class="key-manager-list" [attr.role]="loading() ? 'status' : null" aria-live="polite">
    @if (loading()) { <div class="key-manager-empty">Loading keys...</div> }
    @else if (keys().length === 0) { <div class="key-manager-empty">No keys stored.</div> }
    @else { @for (item of keys(); track item.id) { <div class="key-manager-row"><code class="key-manager-preview">{{ revealed()[item.id] || item.masked_preview }}</code><div class="key-manager-actions"><button class="icon-button subtle" type="button" [attr.aria-label]="revealed()[item.id] ? 'Hide key' : 'Reveal key'" [disabled]="actionKeyId() === item.id" (click)="toggleReveal(item)">{{ revealed()[item.id] ? '◌' : '◉' }}</button><button class="icon-button accent" type="button" [attr.aria-label]="item.is_active ? 'Deactivate key' : 'Activate key'" [disabled]="actionKeyId() === item.id" (click)="toggleActivation(item)">{{ item.is_active ? '⌑' : '✓' }}</button><button class="icon-button danger" type="button" aria-label="Delete key" [disabled]="actionKeyId() === item.id" (click)="deleteKey(item)">×</button></div></div> } }
  </div>
</section>
