// app/client/src/components/HFAccessKeyManager.tsx
import { useState } from 'react';
import DismissibleBanner from './DismissibleBanner';
import HFAccessKeyRow from './HFAccessKeyRow';
import ModalCloseButton from './ModalCloseButton';
import { useHFAccessKeys } from '../hooks/useHFAccessKeys';

type HFAccessKeyManagerProps = {
  isOpen: boolean;
  onClose: () => void;
};

const HFAccessKeyManager = ({ isOpen, onClose }: HFAccessKeyManagerProps) => {
  const [newKeyValue, setNewKeyValue] = useState('');
  const {
    actionKeyId,
    addKey,
    clearError,
    clearRevealedValues,
    deleteKey,
    error,
    keys,
    loading,
    revealedValues,
    submitting,
    toggleActivation,
    toggleReveal,
    visibleRows,
  } = useHFAccessKeys(isOpen);

  const handleAddKey = async (): Promise<void> => {
    const added = await addKey(newKeyValue);
    if (added) {
      setNewKeyValue('');
    }
  };

  const handleClose = (): void => {
    clearRevealedValues();
    onClose();
  };

  if (!isOpen) {
    return null;
  }

  const inputId = 'hf-key-manager-new-key';
  const titleId = 'hf-key-manager-title';
  const descriptionId = 'hf-key-manager-description';

  return (
    <>
      <button
        type="button"
        className="key-manager-backdrop"
        aria-label="Close key manager"
        onClick={handleClose}
      />
      <div
        className="key-manager-popover"
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={descriptionId}
      >
        <header className="key-manager-header">
          <div>
            <p id={titleId} className="panel-label">Hugging Face Keys</p>
            <p id={descriptionId} className="panel-description">
              Store access keys for gated Hugging Face downloads.
            </p>
          </div>
          <ModalCloseButton
            ariaLabel="Close key manager"
            onClick={handleClose}
          />
        </header>

        <div className="key-manager-add-row">
          <label className="sr-only" htmlFor={inputId}>Hugging Face key</label>
          <input
            id={inputId}
            type="password"
            className="text-input"
            placeholder="Enter Hugging Face key"
            value={newKeyValue}
            onChange={(event) => setNewKeyValue(event.target.value)}
          />
          <button
            type="button"
            className="primary-button"
            onClick={() => void handleAddKey()}
            disabled={submitting}
          >
            Add
          </button>
        </div>

        {error && (
          <DismissibleBanner message={error} onDismiss={clearError} />
        )}

        <div className="key-manager-list" role={loading ? 'status' : undefined} aria-live="polite">
          {loading ? (
            <div className="key-manager-empty">Loading keys...</div>
          ) : keys.length === 0 ? (
            <div className="key-manager-empty">No keys stored.</div>
          ) : (
            keys.map((key) => {
              const isVisible = Boolean(visibleRows[key.id]);
              const preview = isVisible
                ? (revealedValues[key.id] || key.masked_preview)
                : key.masked_preview;
              const inProgress = actionKeyId === key.id;

              return (
                <HFAccessKeyRow
                  key={key.id}
                  inProgress={inProgress}
                  isVisible={isVisible}
                  keyItem={key}
                  preview={preview}
                  onDelete={(keyItem) => void deleteKey(keyItem)}
                  onToggleActivation={(keyId, isActive) => void toggleActivation(keyId, isActive)}
                  onToggleReveal={(keyId) => void toggleReveal(keyId)}
                />
              );
            })
          )}
        </div>
      </div>
    </>
  );
};

export default HFAccessKeyManager;

// app/client/angular/app/components/hf-access-key-manager.component.ts
import { Component, EventEmitter, Output, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { DestroyRef } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import { KeysApiService } from '../core/api/keys-api.service';
import { errorMessage } from '../core/api/error-utils';
import type { HFAccessKeyListItem } from '../core/api/api.models';

@Component({
  selector: 'app-hf-access-key-manager',
  imports: [ReactiveFormsModule],
  templateUrl: './hf-access-key-manager.component.html',
})
export class HfAccessKeyManagerComponent {
  private readonly api = inject(KeysApiService);
  private readonly destroyRef = inject(DestroyRef);
  @Output() readonly closed = new EventEmitter<void>();
  protected readonly key = new FormControl('', { nonNullable: true, validators: [Validators.required] });
  protected readonly keys = signal<readonly HFAccessKeyListItem[]>([]);
  protected readonly revealed = signal<Record<number, string>>({});
  protected readonly loading = signal(true);
  protected readonly submitting = signal(false);
  protected readonly actionKeyId = signal<number | null>(null);
  protected readonly error = signal<string | null>(null);

  constructor() { this.load(); }

  private load(): void {
    this.loading.set(true);
    this.api.list().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (response) => { this.keys.set(response.keys); this.loading.set(false); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to load keys.')); this.loading.set(false); } });
  }

  protected addKey(): void {
    if (this.key.invalid) {
      this.key.markAsTouched();
      return;
    }
    this.submitting.set(true);
    this.api.add(this.key.value).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.key.reset(); this.submitting.set(false); this.load(); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to add key.')); this.submitting.set(false); } });
  }

  protected toggleReveal(item: HFAccessKeyListItem): void {
    const existing = this.revealed()[item.id];
    if (existing) { const next = { ...this.revealed() }; delete next[item.id]; this.revealed.set(next); return; }
    this.actionKeyId.set(item.id);
    this.api.reveal(item.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (response) => { this.revealed.set({ ...this.revealed(), [item.id]: response.key_value }); this.actionKeyId.set(null); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to reveal key.')); this.actionKeyId.set(null); } });
  }

  protected toggleActivation(item: HFAccessKeyListItem): void {
    this.actionKeyId.set(item.id);
    const request$ = item.is_active ? this.api.deactivate(item.id) : this.api.activate(item.id);
    request$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.actionKeyId.set(null); this.load(); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to update key.')); this.actionKeyId.set(null); } });
  }

  protected deleteKey(item: HFAccessKeyListItem): void {
    if (!window.confirm(`Delete ${item.masked_preview}?`)) return;
    this.actionKeyId.set(item.id);
    this.api.remove(item.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.actionKeyId.set(null); this.load(); }, error: (error: unknown) => { this.error.set(errorMessage(error, 'Failed to delete key.')); this.actionKeyId.set(null); } });
  }

  protected close(): void {
    this.closed.emit();
  }
}

<button class="key-manager-backdrop" type="button" aria-label="Close key manager" (click)="close()"></button>
<section class="key-manager-popover" role="dialog" aria-modal="true" aria-labelledby="hf-key-title">
  <header class="key-manager-header">
    <div>
      <p id="hf-key-title" class="panel-label">Hugging Face Keys</p>
      <p class="panel-description">Store access keys for gated Hugging Face downloads.</p>
    </div>
    <button class="icon-button subtle" type="button" aria-label="Close key manager" (click)="close()">×</button>
  </header>
  <div class="key-manager-add-row">
    <input id="hf-key-input" class="text-input" type="password" placeholder="Enter Hugging Face key" [formControl]="key" aria-label="Hugging Face key" />
    <button class="primary-button" type="button" (click)="addKey()">Add</button>
  </div>
  @if (error()) { <p class="error-banner" role="alert">{{ error() }}</p> }
  @if (key.invalid && key.touched) {
    <p class="error-banner" role="alert">Enter a Hugging Face key.</p>
  }
  <div class="key-manager-list" [attr.role]="loading() ? 'status' : null" aria-live="polite">
    @if (loading()) { <div class="key-manager-empty">Loading keys...</div> }
    @else if (keys().length === 0) { <div class="key-manager-empty">No keys stored.</div> }
    @else { @for (item of keys(); track item.id) { <div class="key-manager-row"><code class="key-manager-preview">{{ revealed()[item.id] || item.masked_preview }}</code><div class="key-manager-actions"><button class="icon-button subtle" type="button" [attr.aria-label]="revealed()[item.id] ? 'Hide key' : 'Reveal key'" [disabled]="actionKeyId() === item.id" (click)="toggleReveal(item)">{{ revealed()[item.id] ? '◌' : '◉' }}</button><button class="icon-button accent" type="button" [attr.aria-label]="item.is_active ? 'Deactivate key' : 'Activate key'" [disabled]="actionKeyId() === item.id" (click)="toggleActivation(item)">{{ item.is_active ? '⌑' : '✓' }}</button><button class="icon-button danger" type="button" aria-label="Delete key" [disabled]="actionKeyId() === item.id" (click)="deleteKey(item)">×</button></div></div> } }
  </div>
</section>
